unit uFBTypes;

{$mode objfpc}{$H+}

interface

uses
  Classes, SysUtils;

type
  { Firebird Connection Configuration }
  TFBConnectionConfig = record
    ProfileName: string;
    Host: string;
    Port: Integer;
    DatabasePath: string;
    User: string;
    Password: string;
    Charset: string;
    ClientLibrary: string;
    SqlDialect: Integer;
  end;

  { Column definition for Table Designer & MetaData }
  TColumnDef = record
    Name: string;
    DataType: string;     // VARCHAR, BIGINT, INTEGER, TIMESTAMP, etc.
    Size: Integer;        // Para VARCHAR, CHAR
    Scale: Integer;       // Para NUMERIC, DECIMAL
    NotNull: Boolean;
    PrimaryKey: Boolean;
    DefaultValue: string;
    AutoIncrement: Boolean; // FB 3.0+ IDENTITY ou FB 2.5 Generator
  end;

  TColumnDefArray = array of TColumnDef;

  { Helper for Firebird Types }
  TFBMetaTypeHelper = class
  public
    class function FirebirdTypeToString(FieldType, FieldSubType, FieldLength, FieldScale: Integer): string;
    class function BuildColumnSQL(const Col: TColumnDef; FirebirdVersion3Plus: Boolean = True): string;
    class function DefaultConfig: TFBConnectionConfig;
  end;

implementation

{ TFBMetaTypeHelper }

class function TFBMetaTypeHelper.DefaultConfig: TFBConnectionConfig;
begin
  Result.ProfileName := 'Local Firebird';
  Result.Host := 'localhost';
  Result.Port := 3050;
  Result.DatabasePath := '';
  Result.User := 'SYSDBA';
  Result.Password := 'masterkey';
  Result.Charset := 'UTF8';
  Result.ClientLibrary := '';
  Result.SqlDialect := 3;
end;

class function TFBMetaTypeHelper.FirebirdTypeToString(FieldType, FieldSubType, FieldLength, FieldScale: Integer): string;
begin
  case FieldType of
    7:
      if FieldScale < 0 then
        Result := Format('NUMERIC(4,%d)', [-FieldScale])
      else
        Result := 'SMALLINT';
    8:
      if FieldScale < 0 then
        Result := Format('NUMERIC(9,%d)', [-FieldScale])
      else
        Result := 'INTEGER';
    10: Result := 'FLOAT';
    12: Result := 'DATE';
    13: Result := 'TIME';
    14: Result := Format('CHAR(%d)', [FieldLength]);
    16:
      if FieldScale < 0 then
        Result := Format('NUMERIC(18,%d)', [-FieldScale])
      else
        Result := 'BIGINT';
    23: Result := 'BOOLEAN';
    27: Result := 'DOUBLE PRECISION';
    35: Result := 'TIMESTAMP';
    37: Result := Format('VARCHAR(%d)', [FieldLength]);
    261:
      if FieldSubType = 1 then
        Result := 'BLOB SUB_TYPE TEXT'
      else
        Result := 'BLOB';
  else
    Result := Format('UNKNOWN(%d)', [FieldType]);
  end;
end;

class function TFBMetaTypeHelper.BuildColumnSQL(const Col: TColumnDef; FirebirdVersion3Plus: Boolean): string;
var
  S: string;
  DT: string;
begin
  S := Trim(Col.Name) + ' ';
  DT := UpperCase(Trim(Col.DataType));

  if DT = 'VARCHAR' then
  begin
    if Col.Size <= 0 then
      S := S + 'VARCHAR(100)'
    else
      S := S + Format('VARCHAR(%d)', [Col.Size]);
  end
  else if DT = 'CHAR' then
  begin
    if Col.Size <= 0 then
      S := S + 'CHAR(1)'
    else
      S := S + Format('CHAR(%d)', [Col.Size]);
  end
  else if (DT = 'NUMERIC') or (DT = 'DECIMAL') then
  begin
    if Col.Size <= 0 then
      S := S + Format('%s(15,%d)', [DT, Col.Scale])
    else
      S := S + Format('%s(%d,%d)', [DT, Col.Size, Col.Scale]);
  end
  else
    S := S + DT;

  // AutoIncrement (Firebird 3.0+ Identity)
  if Col.AutoIncrement and FirebirdVersion3Plus then
    S := S + ' GENERATED BY DEFAULT AS IDENTITY';

  // Default value
  if Trim(Col.DefaultValue) <> '' then
  begin
    if not (Pos('DEFAULT', UpperCase(Col.DefaultValue)) = 1) then
      S := S + ' DEFAULT ' + Col.DefaultValue
    else
      S := S + ' ' + Col.DefaultValue;
  end;

  // Not Null
  if Col.NotNull or Col.PrimaryKey then
    S := S + ' NOT NULL';

  Result := S;
end;

end.
